language: node_js
node_js: stable

sudo: false

install: true  # yarn bug

addons:
  firefox: latest
  chrome: stable

os:
  - linux
#  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated xctool || brew upgrade xctool; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install google-chrome; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

before_script:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi


after_failure:
  - cat /home/travis/build/vyakymenko/angular-seed-express/npm-debug.log

branches:
  only: master

notifications:
  email: true

cache:
  directories:
    - "$HOME/.npm"

script:
#  - npm run tests.all
  - npm run test
